---

- name: configure ansible server
  hosts: localhost

  tasks:

    - name: rename host
      hostname:
        name: ansible-server

    - name: add nameservers temporarily
      shell: echo -e "nameserver 192.168.50.2\nnameserver 192.168.50.3" > /etc/resolv.conf

    - name: name in host file
      lineinfile:
        path: /etc/hosts
        line: "{{ansible_eth1.ipv4.address}} ansible-server ansible-server.ad.skoopycorp.com"

    - name: install realmd and deps
      yum:
        name:
          - realmd
          - sssd
          - oddjob
          - adcli
          - oddjob-mkhomedir
          - gcc
          - samba-common
          - samba-common-tools
          - krb5-workstation
          - krb5-devel
          - python3-devel
          - python3-kerberos
        state: present

    - name: join domain
      shell: echo "vagrant" | realm join "AD.SKOOPYCORP.COM" -U Administrator --computer-ou=OU=servers,DC=ad,DC=skoopycorp,DC=com
      args:
        creates: /etc/sssd/sssd.conf

    - name: enable dyn dns
      ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ad.skoopycorp.com
        option: "{{item.key}}"
        value: "{{item.value | string}}"
      register: sssd_updated
      with_dict:
        dyndns_update: True
        dyndns_update_ptr: True

    - name: start and enable sssd
      service:
        name: sssd
        state: restarted
        use: service
      when: sssd_updated.changed