---
- name: deploy domain controller
  hosts: 192.168.50.2


  tasks:

    - name: set host name
      win_hostname:
        name: dc1

    - name: install features
      win_feature:
        name: "{{item}}"
        state: present
      with_items:
        - ad-domain-services
        - dns
      register: features

    - name: reboot if features installed
      win_reboot:
        reboot_timeout: "{{reboot_timeout}}"
      when: features.changed

    - name: deploy domain
      win_domain:
        dns_domain_name: ad.skoopycorp.com
        safe_mode_password: What a password!
      register: domain_deploy

    - name: final reboot
      win_reboot:
        reboot_timeout: "{{reboot_timeout}}"
      when: domain_deploy.changed

    - pause:
        minutes: 6
      when: domain_deploy.changed

    - name: add wsman service principal to dc1
      win_shell: Set-ADComputer dc1 -ServicePrincipalNames @{Add="{{item}}"}
      args:
        executable: powershell
      when: domain_deploy.changed
      with_items:
        - WSMAN/DC1
        - WSMAN/dc1.ad.skoopycorp.com

    - name: copy files
      win_copy:
        src: "{{item}}"
        dest: C:\
      with_items:
        - policy_package.zip
        - AdmPwd.PS.zip
        - PolicyDefinitions.zip

    - name: install laps powershell module
      win_unzip:
        src: C:\AdmPwd.PS.zip
        dest: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
        creates: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AdmPwd.PS\

    - name: unzip gpo shared policy defs
      win_unzip:
        src: C:\PolicyDefinitions.zip
        dest: C:\Windows\SYSVOL\sysvol\ad.skoopycorp.com\policies\
        creates: C:\Windows\SYSVOL\sysvol\ad.skoopycorp.com\policies\PolicyDefinitions

    - name: add server ou
      win_shell: New-ADOrganizationalUnit -Name servers -Path "dc=ad,dc=skoopycorp,dc=com"
      args:
        executable: powershell
      when: domain_deploy.changed

    - name: deploy laps AD entries
      win_shell: "{{item}}"
      args:
        executable: powershell
      with_items:
        - Update-AdmPwdADSchema
        - Set-AdmPwdComputerSelfPermission -Identity "ou=servers,dc=ad,dc=skoopycorp,dc=com"
      when: domain_deploy.changed

    - name: load GPOs
      script: ../scripts/Backup-DomainGroupPolicies/Backup-DomainGroupPolicies.ps1 -Path C:\policy_package.zip -Restore
      when: domain_deploy.changed

    - name: set dns ethernet
      win_dns_client:
        adapter_names: "{{item}}"
        ipv4_addresses:
          - "{{ansible_ip_addresses[2]}}"
          - 127.0.0.1
      with_items:
        - ethernet
        - ethernet 2
