---

- name: deploy domain joined windows server
  hosts: windows_servers


  tasks:

    - name: set dns on ethernet
      win_dns_client:
        adapter_names: ethernet
        ipv4_addresses:
          - 192.168.50.2
          - 192.168.50.3

    - name: set dns on ethernet 2
      win_dns_client:
        adapter_names: ethernet 2
        ipv4_addresses:
          - 192.168.50.2
          - 192.168.50.3

    - name: add rsat tools
      win_feature:
        name: RSAT
        state: present
        include_sub_features: yes
        include_managment_tools: yes

    - name: join domain
      win_domain_membership:
        hostname: "{{host_name}}"
        dns_domain_name: ad.skoopycorp.com
        domain_admin_user: administrator@ad.skoopycorp.com
        domain_admin_password: vagrant
        state: domain
      register: domain_member

    - name: reboot
      win_reboot:
      when: domain_member.changed